DROP DATABASE IF EXISTS `CheckpointsCambridge_Live`;
DROP DATABASE IF EXISTS `Interactive_Live`;
DROP DATABASE IF EXISTS `epub2`;
DROP DATABASE IF EXISTS `hub_import`;
DROP DATABASE IF EXISTS `kat`;
/* DROP DATABASE IF EXISTS `tmp`; */