<?php
defined('C5_EXECUTE') or die("Access Denied.");

$subject = t("Cambridge GO Password Reset Confirmation");
$body = t("

Dear %s,

You recently requested a new password. Please click the link below to complete your new password request: 

%s . 

If you are unable to click the link, simply copy and paste it into your web browser. If you did not request a new password, someone may have been trying to access your account without your permission. As long you do not click the link contained in the email, no action will be taken and your account will remain secure.

The Cambridge GO Team

**************************************************

This is an automated email generated by the

Education website for Cambridge University Press

Australia and New Zealand. Please do not reply to

to this email.

If you have any questions, contact Customer

Service via email enquiries@cambridge.edu.au or

phone +61 (0)3 8671 1400.

(FreePhone within Australia 1800 005 210,

or if within New Zealand 0800 023 520)

**************************************************

", $firstName, $changePassURL);