<?php
defined('C5_EXECUTE') or die("Access Denied.");

$subject = SITE . " " . t("Account Confirmation");
$body = t(" Hi %s, 
    
Thank you for registering with Cambridge GO.

Your account has been created.

To activate your account, open the following link:

%s 

If you are unable to click the link, simply copy and paste it into your web browser.

The Cambridge GO team.

**************************************************

This is an automated email generated by the

Education website for Cambridge University Press

Australia and New Zealand. Please do not reply to

to this email.

If you have any questions, contact Customer

Service via email enquiries@cambridge.edu.au or

phone +61 (0)3 8671 1400.

(FreePhone within Australia 1800 005 210,

or if within New Zealand 0800 023 520)

**************************************************

", $uFirstName, BASE_URL . View::url('/go/login', 'v', $uHash));