<?php

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * Description of forgot_password
 *
 * @author paulbalila
 */
class GoForgotPasswordController extends Controller
{
    public function on_start() {
        $v = View::getInstance();
        $v->setTheme(PageTheme::getByHandle("go_theme"));
        $this->error = Loader::helper('validation/error');
        $html = Loader::helper('html');
        $this->addHeaderItem('<script type="text/javascript" src="' . (string)$html->javascript(
            'forgotPassword.js', 'go_contents')->href . '?v=2"></script>');
    }

    public function view($status = '',$email = '')
    {
        if($status) {
            $this->set('status',$status);
            $this->set('email',$email);
        }
    }

    public function forgot_pass()
    {
        $loginData['success'] = 0;

        $vs = Loader::helper('validation/strings');
        $em = $this->post('uEmail');

        try {
            if (!$vs->email($em)) {
                throw new Exception(t('Invalid email address.'));
            }

            $oUser = UserInfo::getByEmail($em);
            
            if (!$oUser) {
                $this->set('errorMsg','We have no record of that email address.');
                throw new Exception(t('We have no record of that email address.'));
            }

            $mh = Loader::helper('mail');

            $fname = $oUser->getAttribute('uFirstName');
            $mh->addParameter('firstName',$fname);
            $mh->to($oUser->getUserEmail());

            //generate hash that'll be used to authenticate user, allowing them to change their password
            $uHash = UserValidationHash::add($oUser->getUserID(), UVTYPE_CHANGE_PASSWORD);

            $changePassURL = BASE_URL . View::url('/go/forgot_password', 'change_password', $uHash);
            $mh->addParameter('changePassURL', $changePassURL);

            $mh->addParameter('bodyHTML',  $this->getForgotPassHTML($fname, $changePassURL));

            $mh->from('go@cambridge.edu.au', t('Cambridge GO'));
            
            $mh->load('forgot_password','go_contents'); // get mail template from package
            @$mh->sendMail();

            $loginData['success'] = 1;
            $loginData['msg'] = $this->getPasswordSentMsg();

        } catch (Exception $e) {
            $this->error->add($e);
            $loginData['error'] = $e->getMessage();
        }

        if ($_REQUEST['format'] == 'JSON') {
            $jsonHelper = Loader::helper('json');
            echo $jsonHelper->encode($loginData);
            die;
        }

        if ($loginData['success'] == 1) {
            $this->redirect('/go/forgot_password','password_sent',$oUser->getUserEmail());
        }
    }
    
    public function change_password($uHash = '')
    {
        $this->set('doChangePassword', true);
    }
    
    private function getForgotPassHTML($fname, $changePassURL)
    {
        $html = '';
        $html .= '<p>Dear ' . $fname . ',</p>';
        $html .= '<br />';
        $html .= '<p>You recently requested a new password. Please click the link below to complete your new password request: </p>';
        $html .= '<br />';
        $html .= $changePassURL;
        $html .= '<br />';
        $html .= '<p>If you are unable to click the link, simply copy and paste it into your web browser. If you did not request a new password, someone may have been trying to access your account without your permission. As long you do not click the link contained in the email, no action will be taken and your account will remain secure.</p>';
        $html .= '<br />';
        $html .= '<p>The Cambridge GO Team</p>';
        $html .= '<br />';
        $html .= '<p>**************************************************<br />'
                . 'This is an automated email generated by the<br />'
                . 'Education website for Cambridge University Press<br />'
                . 'Australia and New Zealand. Please do not reply to<br />'
                . 'to this email.'
                . 'If you have any questions, contact Customer<br />'
                . 'Service via email enquiries@cambridge.edu.au or<br />'
                . 'phone +61 (0)3 8671 1400.<br />'
                . '(FreePhone within Australia 1800 005 210,<br />'
                . 'or if within New Zealand 0800 023 520)</p>';
        $html .= '<p>**************************************************</p>';
        return $html;
    }

}
